# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotenv < Formula
  desc ""
  homepage "https://github.com/javif89/dotenv"
  version "0.0.5"

  on_macos do
    url "https://github.com/javif89/dotenv/releases/download/v0.0.5/dotenv_0.0.5_darwin_all.tar.gz"
    sha256 "ffa8e9ad86181173684cd2d949c7e74fdab53f8e35ffe477081ddc4172e460ef"

    def install
      bin.install "dotenv"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/javif89/dotenv/releases/download/v0.0.5/dotenv_0.0.5_linux_arm64.tar.gz"
      sha256 "070cdd2b498c92261df1f3a245580b284e6a1eb60950d2c787503e0f409c25fa"

      def install
        bin.install "dotenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/javif89/dotenv/releases/download/v0.0.5/dotenv_0.0.5_linux_amd64.tar.gz"
      sha256 "fa7ccd382910051755945314ffa0ce2f88088c097ff893687d4244dcb270be68"

      def install
        bin.install "dotenv"
      end
    end
  end
end
