# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docit < Formula
  desc ""
  homepage "https://github.com/javif89/docit"
  version "0.1.0"

  on_macos do
    url "https://github.com/javif89/docit/releases/download/v0.1.0/docit_0.1.0_darwin_all.tar.gz"
    sha256 "c6dc430f2cde5acb424c2ff6097447cea9e16948925d8d9fd12a0254178753e3"

    def install
      bin.install "docit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/javif89/docit/releases/download/v0.1.0/docit_0.1.0_linux_arm64.tar.gz"
      sha256 "5a65ceb3317bd9bb3d2e6e714fbc5c760c29f2d0e219b233e12f7534bbfcee1a"

      def install
        bin.install "docit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/javif89/docit/releases/download/v0.1.0/docit_0.1.0_linux_amd64.tar.gz"
      sha256 "107a3a4e2075bf768fb18edea41d5478ff26369b2d854aba2cc8e9b069a542fd"

      def install
        bin.install "docit"
      end
    end
  end
end
