# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotenv < Formula
  desc ""
  homepage "https://github.com/javif89/dotenv"
  version "0.0.6"

  on_macos do
    url "https://github.com/javif89/dotenv/releases/download/v0.0.6/dotenv_0.0.6_darwin_all.tar.gz"
    sha256 "445bfd9f3e6ce706755f44737b9714dfd0e8de47ae76ffadec8a33bc5969d16f"

    def install
      bin.install "dotenv"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/javif89/dotenv/releases/download/v0.0.6/dotenv_0.0.6_linux_arm64.tar.gz"
      sha256 "b4911b367cde6862521bfea8a8b638fdfe663f3b126c59fc5ab1c71f8ef151bb"

      def install
        bin.install "dotenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/javif89/dotenv/releases/download/v0.0.6/dotenv_0.0.6_linux_amd64.tar.gz"
      sha256 "ef42d6f58eea6d1bc92432d3c4960dfa617e97afb2fffabe021dc56dc92bab3e"

      def install
        bin.install "dotenv"
      end
    end
  end
end
