# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotenv < Formula
  desc ""
  homepage "https://github.com/javif89/dotenv"
  version "0.0.4"

  on_macos do
    url "https://github.com/javif89/dotenv/releases/download/v0.0.4/dotenv_0.0.4_darwin_all.tar.gz"
    sha256 "a12ce84763c4b28f9d0a8bc851563f41886be897cd12ebf39b184e7b733020f0"

    def install
      bin.install "dotenv"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/javif89/dotenv/releases/download/v0.0.4/dotenv_0.0.4_linux_arm64.tar.gz"
      sha256 "23928d9bf80d523bfc483ed739d437d360889ca7475d6cb80daceed4259ec2b3"

      def install
        bin.install "dotenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/javif89/dotenv/releases/download/v0.0.4/dotenv_0.0.4_linux_amd64.tar.gz"
      sha256 "14bf75e920a1127d2c1e906e068f650a86dfc77394842d28f54c9a8d91939920"

      def install
        bin.install "dotenv"
      end
    end
  end
end
